version: '3'

services:


  consumer:
    build: ./app
    volumes:
     - ./app:/app
    ports:
     - "8000:80"
    environment:
     - PORT=80
    #command: python -u consumer.py --source ecommerce
    command: sleep infinity
