version: '3'

services:

  producer:
    build: ./app
    volumes:
     - ./app:/app
    ports:
     - "80:80"
    environment:
     - PORT=80
    command: uvicorn producer:app --host 0.0.0.0 --port 80 --reload

  consumer:
    build: ./app
    volumes:
     - ./app:/app
    ports:
     - "8000:80"
    environment:
     - PORT=80
    command: python -u consumer.py
    #sleep infinity
    depends_on:
     - producer
